---
type: chart
#
#rootfs:
#  - image: samsung_cnct/fluentd-container
#    dockerContext: rootfs/fluentd
#    context: fluentd
#    chart: fluentd
#    value: image
configs:
  - chart: fluentd
    timeout: 600
    retries: 1
    release: fluentd
prod:
  doDeploy: none
